let knowledgeBase = [];

const stopWords = new Set([
    "a", "an", "and", "are", "as", "at", "be", "but", "by", "can", "could", "do",
    "does", "for", "from", "get", "give", "has", "have", "how", "i", "if", "in",
    "is", "it", "me", "my", "of", "on", "or", "our", "should", "the", "their",
    "there", "they", "this", "to", "up", "was", "we", "what", "when", "where",
    "who", "why", "with", "you", "your"
]);

const form = document.querySelector("#question-form");
const input = document.querySelector("#question");
const answer = document.querySelector("#answer");
const sources = document.querySelector("#sources");
const quickQuestions = document.querySelectorAll("[data-question]");
const sourceStatus = document.querySelector("#source-status");

function tokenize(text) {
    return text
        .toLowerCase()
        .replace(/[^a-z0-9\s]/g, " ")
        .split(/\s+/)
        .filter((word) => word.length > 1 && !stopWords.has(word));
}

function termFrequency(tokens) {
    return tokens.reduce((counts, token) => {
        counts[token] = (counts[token] || 0) + 1;
        return counts;
    }, {});
}

function scoreDocument(questionTokens, documentText) {
    const questionCounts = termFrequency(questionTokens);
    const documentCounts = termFrequency(tokenize(documentText));
    const sharedTerms = Object.keys(questionCounts).filter((term) => documentCounts[term]);

    return sharedTerms.reduce((score, term) => {
        return score + questionCounts[term] * documentCounts[term];
    }, 0);
}

function retrieve(question) {
    const questionTokens = tokenize(question);

    const scoredDocs = knowledgeBase
        .map((doc) => ({
            ...doc,
            score: scoreDocument(questionTokens, `${doc.title} ${doc.category} ${doc.content}`)
        }))
        .sort((a, b) => b.score - a.score);

    const relevantDocs = scoredDocs.filter((doc) => doc.score > 0);
    return (relevantDocs.length > 0 ? relevantDocs : scoredDocs).slice(0, 4);
}

function generateAnswer(question, retrievedDocs) {
    const relevantDocs = retrievedDocs.filter((doc) => doc.score > 0);

    if (!question) {
        return "<p>Please type a customer support question to start the RAG process.</p>";
    }

    if (relevantDocs.length === 0) {
        return `
            <p>I could not find a strong answer in <strong>policy.json</strong> for: <strong>${escapeHtml(question)}</strong></p>
            <p>This is an important RAG behavior: when the knowledge source does not contain enough context, the app should avoid inventing an answer.</p>
        `;
    }

    const primary = relevantDocs[0];
    const supporting = relevantDocs.slice(1, 3);
    const supportingItems = supporting
        .map((doc) => `<li><strong>${escapeHtml(doc.title)}:</strong> ${escapeHtml(doc.content)}</li>`)
        .join("");

    return `
        <p><strong>Answer:</strong> ${escapeHtml(primary.answer)}</p>
        <p>The answer was generated from <strong>policy.json</strong>, mainly from the policy section <strong>${escapeHtml(primary.title)}</strong>.</p>
        ${supportingItems ? `<p>Additional retrieved context:</p><ul>${supportingItems}</ul>` : ""}
    `;
}

function renderSources(retrievedDocs) {
    if (retrievedDocs.every((doc) => doc.score === 0)) {
        sources.innerHTML = "<li><strong>No matching policy section found</strong><p>The policy file does not contain enough context for this question.</p></li>";
        return;
    }

    sources.innerHTML = retrievedDocs
        .filter((doc) => doc.score > 0)
        .map((doc) => `
            <li>
                <span class="score">Match score: ${doc.score}</span>
                <strong>${escapeHtml(doc.title)}</strong>
                <small>${escapeHtml(doc.category)} · Source: policy.json</small>
                <p>${escapeHtml(doc.content)}</p>
            </li>
        `)
        .join("");
}

function escapeHtml(value) {
    return String(value)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
}

function runRag(question) {
    const retrievedDocs = retrieve(question);
    renderSources(retrievedDocs);
    answer.innerHTML = generateAnswer(question, retrievedDocs);
}

async function loadPolicyFile() {
    try {
        const response = await fetch("policy.json");

        if (!response.ok) {
            throw new Error(`Policy file request failed with status ${response.status}`);
        }

        const data = await response.json();
        knowledgeBase = data.policies;
        sourceStatus.textContent = `Knowledge source: policy.json (${knowledgeBase.length} policy sections, generated by ChatGPT)`;
        runRag(input.value.trim());
    } catch (error) {
        sourceStatus.textContent = "Knowledge source could not be loaded.";
        answer.innerHTML = `
            <p><strong>policy.json could not be loaded.</strong></p>
            <p>Please run this folder through a local web server, then open the app from localhost. Example: <code>python -m http.server 8765</code></p>
        `;
        sources.innerHTML = "";
    }
}

form.addEventListener("submit", (event) => {
    event.preventDefault();
    runRag(input.value.trim());
});

quickQuestions.forEach((button) => {
    button.addEventListener("click", () => {
        input.value = button.dataset.question;
        runRag(input.value);
    });
});

loadPolicyFile();
